SELECT 'янв' AS label, 2 AS Процент FROM DUAL 
UNION 
SELECT 'фев', 3 FROM DUAL 
UNION 
SELECT 'март', 33 FROM DUAL 
UNION 
SELECT 'апрель', 3 FROM DUAL 
UNION 
SELECT 'май', 4 FROM DUAL 
UNION 
SELECT 'июнь', 3 FROM DUAL 
UNION 
 SELECT 'июль', 11 FROM DUAL 
UNION 
SELECT 'август', 2 FROM DUAL 
UNION 
SELECT 'чент', 3 FROM DUAL 