WITH TT AS
(
select
  XDATA
, TO_NUMBER(YDATA) as YDATA
, DATASET_NAME
, FILTER_NAME
, FILTER_DATA
from DASHBOARD_DATA
where
     ELEMENT_ID = 'paidPlan'
 and COALESCE(IS_ACTIVE, '1') = '1'
 and XDATA = TO_CHAR(SYSDATE, 'mm.yyyy')
)
SELECT distinct
  ' '||COALESCE(d.SHORT_NAME, d.NAME) as "Департамент"
, TO_CHAR(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN' and t.FILTER_DATA = tt.FILTER_DATA), 0), '999G999G999G999G999G990D00') as "ПЛАН"
, TO_CHAR(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'FACT' and t.FILTER_DATA = tt.FILTER_DATA), 0), '999G999G999G999G999G990D00') as "ФАКТ"
, TO_CHAR(case
    when COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN' and t.FILTER_DATA = tt.FILTER_DATA), 0) != 0
       then
         ROUND(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'FACT' and t.FILTER_DATA = tt.FILTER_DATA), 1)
        /(SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN' and t.FILTER_DATA = tt.FILTER_DATA)*100, 2)
       else 0
  end, '999G999G999G999G999G990D00') "% выполнения"
FROM TT tt JOIN DEPARTMENT d ON tt.FILTER_DATA = TO_CHAR(d.ID_DEPARTMENT)
WHERE
   tt.YDATA > 0
UNION ALL
SELECT distinct
  'ВСЕГО: '
, TO_CHAR(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN'), 0), '999G999G999G999G999G990D00') as "ПЛАН"
, TO_CHAR(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'FACT'), 0), '999G999G999G999G999G990D00') as "ФАКТ"
, TO_CHAR(case
    when COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN'), 0) != 0
       then
         ROUND(COALESCE((SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'FACT'), 1)
        /(SELECT SUM(COALESCE(t.YDATA, 0)) FROM TT t WHERE t.XDATA = tt.XDATA and t.DATASET_NAME = 'PLAN')*100, 2)
       else 0
  end, '999G999G999G999G999G990D00') "% выполнения"
FROM TT tt
ORDER BY 1